### PR TITLE
Added nicer default values

### PR DESCRIPTION
**Pull request by kordianbruck**
Fix for issue #184

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Thanks for the PR. Could you please remove the gitignore file and keep the order of the entries in the array so only really changed lines are removed/added.

**Comment by raimund-schluessler** [comment]
Wait... I remember to set the ```'show' => 2 lines``` in order to automatically show the collections by default. Is this the behaviour you see? Do the collections show when they have entries by default?

**Comment by kordianbruck** [comment]
The changes in the order is intended so that it's more logically sorted. 

No, they don't show up on default, so dunno...

**Comment by simonleber** [comment]
:+1:

**Comment by raimund-schluessler** [comment]
Why do you set the default values differently? Don't you think they should all be shown by default?

**Comment by raimund-schluessler** [comment]
Also, how is this more logical?

**Comment by kordianbruck** [comment]
This was a suggestion from @Henni to have different defaults to show off the functionality. I also think this is a good idea, as you don't need the starred collection when there are no starred items.

Well it somehow does not make sense to me to have 'all' somewhere in the middle. I feel like it is a general internet thing. Also it is the default page when entering the task app.

**Comment by raimund-schluessler** [comment]
Your PR doesnt allow to hide the collections as ```empty()``` is true for ```0```. I fixed this with https://github.com/owncloud/tasks/commit/b9d24ae5e3b12b998fa2868a2c121a52bbd2fd65

We can discuss about the default value, but I think the collections should be set to automatically by default.

**Pull request closed without merging**
