### PR TITLE
Fixed new tasks being starred by default

### PR DESCRIPTION
**Pull request by Henni**
fixes a part of #179

### CODE REVIEW

**Comment by kordianbruck** [comment]
Looks good for me...

**Comment by raimund-schluessler** [comment]
I am ok with merging this, as it really fixes the starring issue. However, I plan to integrate setting the priority in more detail soon, so this might change again anyway ;)

**Comment by Henni** [comment]
Great! Are you planing to work on the idea with color coded priorities from #165 ?

**Comment by raimund-schluessler** [comment]
I don't know if this is really intuitiv as you have to remember which color means which priority. I will first implement the setting of the priority at the front-end and server side, then we can think about how to show the priority best.

**Comment by Henni** [comment]
Do you think we should still keep the star even if you add more granular priority?

**Pull request merged**
