### PR TITLE
Shortened animations

### LINKED ISSUE #188: Animations take too long
The animation to show the task details takes to long and may annoy users.
When switching between lists the tasks seem to be reordered. This could irritate the users.

We should probably remove the animation between lists and shorten or remove the animation for the task details.
Maybe it is even a good idea to always show the task details.

### PR DESCRIPTION
**Pull request by Henni**
fixes #188

@jancborchardt please have a look at this.

### CODE REVIEW

**Comment by jancborchardt** [comment]
For the apps and user menu we actually use 50ms (OC.menuSpeed). What do you think about that – maybe too fast here but just asking. :)

**Comment by jancborchardt** [comment]
cc @owncloud/designers for review.

**Comment by Henni** [comment]
@jancborchardt I tried 50ms and it is too fast in my opinion.
I also found some occurrences of OC.menuSpeed*4 like here: https://github.com/owncloud/core/blob/9a0b0ba4889142d1b105bcf7df2b5b79864b8013/core/js/apps.js#L47
So I used this instead.

**Comment by jancborchardt** [comment]
@Henni right, that’s the speed we use for the settings pane so that might be better. Can you use OC.menuSpeed * 4 there as well? (Or maybe we should define OC.menuSpeedSlower in core?)

**Comment by Henni** [comment]
@jancborchardt I don't think there is a way to get this variable into the css code and I don't like a workaround with javascript.
Maybe we could add a css class to core which just defines a transition-speed which could then be used by app developers.

**Comment by raimund-schluessler** [comment]
I find 0.2 s a bit short, but ok.

**Comment by jancborchardt** [comment]
Everything slower than 100ms already feels like it’s non instant, so we shouldn’t go too much over this. 200ms seems like a good call.

**Pull request merged**
