### PR TITLE
Integrate Appframework Relics

### PR DESCRIPTION
**Pull request by raimund-schluessler**
I integrated the relics of the appframework into the app and removed all not needed files.

@Henni Please have a look.

### CODE REVIEW

**Comment by Henni** [comment]
@raimund-schluessler what is the goal of this PR?

**Comment by raimund-schluessler** [comment]
@Henni Functionality is not affected, but we get rid of https://github.com/owncloud/tasks/blob/master/js/vendor/appframework/app.js which is 1720 lines large and replace it with somewhat over 300 lines in https://github.com/owncloud/tasks/blob/master/js/public/app.js Means we save 1400 lines of code and don't have to load a separate javascript file. Furthermore, we can maintain all the request and model related stuff better as is it written in Coffeescript now (In case we want to get rid of coffeescript some day: the javascript, which will be replaced, was compiled from coffeescript anyway ;) )

We just have to test if everything works like before, which is the case for my installations.

**Comment by Henni** [comment]
The 'add list' input isn't focused by default anymore.

I haven't found any other bugs yet. But I'll test it a bit.

**Comment by raimund-schluessler** [comment]
Thanks for the hint, I missed adding a directive. I added it now. I will rebase before merge.

**Comment by Henni** [comment]
looks good :+1:

**Pull request merged**
