### PR TITLE
move functionality from taskscontroller to service

### PR DESCRIPTION
**Pull request by Henni**
I proposed similar changes before the sabre/vobject changes #158.
This moves most of the functionality out of taskscontroller.php into tasksservice.php.

### CODE REVIEW

**Comment by Henni** [comment]
PHP 5.3 doesn't like my code :( . I'm looking into it...

**Comment by raimund-schluessler** [comment]
I guess we could just drop support for php 5.3 as owncloud 8.0 requires php 5.4 anyway and the tasks app requires even oC8.1:
https://doc.owncloud.org/server/8.0/admin_manual/release_notes.html

**Comment by Henni** [comment]
Owncloud recommends PHP 5.4 but requires only 5.3.8 (See [manual Installation](https://doc.owncloud.org/server/7.0/admin_manual/installation/source_installation.html) )

**Comment by raimund-schluessler** [comment]
This was the link for 7.0. For 8.0 php 5.4 is required: https://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html

**Comment by Henni** [comment]
Can we merge this now and rebase #199 on top of this? Or would you do it a different way @raimund-schluessler ?

**Comment by raimund-schluessler** [comment]
In principle we can merge #195 before #199, but I would like to have a look at it before. ;) will do tomorrow. 

Von meinem iPhone gesendet

**Comment by raimund-schluessler** [comment]
Everything seems to work. I hope with https://github.com/owncloud/tasks/commit/eff802f181a9838ed49c6f084ecb40d363606555 the php 5.3 checks should be removed.

**Pull request merged**
