### PR TITLE
Moved functionality from taskscontroller.php to a new service

### PR DESCRIPTION
**Pull request by Henni**
I moved almost all functionality from the taskscontroller.php to a new file tasksservice.php to prepare the MVC model for a REST implementation.

I believe this is necessary to implement APIs as requested in #76.
Even without the need for a REST API this restructuring should clean up the code.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Thanks for the work and sorry for my long response time. I think the intention to move all the actual work into a service is very good, but I think we should not merge it directly into master but rather into a branch for more refactoring of the service. This branch could then be used to apply possibly necessary changes for oc 8.1 as they switched to sabre/dav 2.1 as far as I know.

I will be on a business trip for the next two weeks, so I can look into this at the beginning of May at the earliest.

**Comment by Henni** [comment]
Thank you for your feedback @raimund-schluessler.
I'll have a look into further refactoring the code in an new branch.
I'm planning to have a look at the other controllers and moving their functionality to services as well.

What "necessary changes for oc 8.1" do you mean?

**Comment by raimund-schluessler** [comment]
Necessary changes  can be found here https://github.com/owncloud/tasks/pull/159 and here https://github.com/owncloud/core/pull/15691. Some work has already been done, but it doesn't seem to work yet.

**Comment by raimund-schluessler** [comment]
Maybe we just use the branch https://github.com/owncloud/tasks/tree/sabre-upgrade2.1 to move the functionality into services.

**Comment by Henni** [comment]
As soon as #159 is done I'll redo this refactoring.

**Pull request closed without merging**
