### PR TITLE
removed bracket

### PR DESCRIPTION
**Pull request by simonleber**
removed bracket from bootstrap.css

### CODE REVIEW

**Comment by simonleber** [comment]
removed bracket from bootstrap.css

**Comment by Henni** [comment]
@raimund-schluessler maybe we should add a css/less-linter to prevent this in the future.

**Comment by raimund-schluessler** [comment]
@Henni Yeah, we could do so, altough I guess the less files do not compile with such errors.

**Comment by Henni** [comment]
@raimund-schluessler maybe we could remove the less files all together?
It looks to me like less isn't really necessary for our use case.
if you like we could talk about this on irc if you have gotten around setting it up.

**Pull request merged**
