### PR TITLE
[WIP] Make Tasks a DAV client, close #280

### LINKED ISSUE #280: Switch to unified CalDAV endpoint
Migrate to the unified CalDAV endpoint in core to get rid of the dependency to the calendar app.
See https://github.com/owncloud/core/pull/20371

### PR DESCRIPTION
**Pull request by raimund-schluessler**
We want to get rid of the calendar dependency and use the CalDAV server build-in in oC core 9.x.

In order to hopefully make the development easier the same DAV library as in core and calendar will be used. No more server side CalDAV stuff in the app itself.

Todos:

***Calendars***
- [x] Get calendars
- [x] Create calendar
- [x] Delete calendar
- [x] Rename calendar

***Tasks***
- [x] Get tasks
- [x] Create task (subtask)
- [x] Fix creating tasks in the collection views
- [x] Toggle subtasks visibility
- [x] Delete task
- [x] Toggle task state
- [x] Rename task
- [x] Set task priority
- [x] Set start date
- [x] Set end date
- [x] Set progress
- [x] Edit categories
- [x] Edit note
- [x] Change calendar
- [x] Respect write privileges for drag-n-drop
- [x] Creating subtasks in "All" view does not work
- [x] Only load uncomplete tasks, load completed tasks on demand
- [x] Load completed subtasks when opening parent task
- [ ] Respect timezone setting for start, due and reminder
- [ ] Enable copying tasks
- [ ] Set reminder (with notification support)
- [ ] Implement comments

***Various***
- [x] Check compliance ```./occ app:check-code tasks```
- [x] Add makefile for appstore packaging
- [x] Add an issue template

***Search***
- [ ] Implement search provider

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@georgehrke @raghunayyar I would like to use your implementation of the client side calendar service and maybe other files from the calendar-rework if its ok with you.

**Comment by georgehrke** [comment]
> I would like to use your implementation of the client side calendar service and maybe other files from the calendar-rework if its ok with you.

Sure, it's free software, go ahead :)

**Comment by raimund-schluessler** [comment]
Can someone tell me if it is possible to also get the id of a calendar? If yes, how has the request body to look like?

I tried something like this
```
<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:aapl="http://apple.com/ns/ical/" xmlns:oc="http://owncloud.org/ns" xmlns:cs="http://calendarserver.org/ns/">
  <d:prop>
    <d:displayname />
    <d:id />
    <c:id />
    <aapl:id />
    <c:calendar-description />
    <c:calendar-timezone />
    <aapl:calendar-order />
    <aapl:calendar-color />
    <c:supported-calendar-component-set />
    <oc:calendar-enabled />
    <d:acl />
    <d:owner />
    <oc:invite />
  </d:prop>
</d:propfind>
```
but this does not return an id. @DeepDiver1975 @georgehrke maybe?

**Comment by georgehrke** [comment]
`<d:href>/remote.php/dav/calendars/admin/personal/</d:href>` is unique. I don't think you can get the database id. It wouldn't be of any use anyway, because you always need the url.

**Comment by raimund-schluessler** [comment]
> It wouldn't be of any use anyway, because you always need the url.

 Yes, that's true. But I need something to show in the address bar when a user opens a calendar, so the page history works correctly. The database ID would have been the easiest solution.

**Comment by georgehrke** [comment]
The display name is supposed to be unique. Although I'm not sure this if this is enforced at the moment.

**Comment by raimund-schluessler** [comment]
The displayname is currently not enforced to be unique and it won't be for different users.

For the moment I will just count upwards, but this might result in a usability problem when a user bookmarks the link to a certain calendar. I will have to think of a better solution later on.

**Comment by DeepDiver1975** [comment]
The displayname is indeed not unique. But the Uri is.

**Comment by raimund-schluessler** [comment]
The Uri also seems to only be unique for one user. But when User1 shares a calendar with the (for him) unique Uri 'test' with User2 which also has a calendar with this Uri, User2 has two calendars with the same Uri. Hence, only the principaluri is really unique, or am I wrong?

**Comment by DeepDiver1975** [comment]
The shared Uri will be test_shared_by_user1

**Comment by raimund-schluessler** [comment]
> The shared Uri will be test_shared_by_user1

Ah, alright, thank you.
Can I query the Uri directly, or do I have to extract it from the url?
The request
```
<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:aapl="http://apple.com/ns/ical/" xmlns:oc="http://owncloud.org/ns" xmlns:cs="http://calendarserver.org/ns/">
  <d:prop>
    <d:displayname />
    <d:uri />
    <c:uri />
    <aapl:uri />
    <oc:uri />
    <c:calendar-description />
    <c:calendar-timezone />
    <aapl:calendar-order />
    <aapl:calendar-color />
    <c:supported-calendar-component-set />
    <oc:calendar-enabled />
    <d:acl />
    <d:owner />
    <oc:invite />
  </d:prop>
</d:propfind>
```
does not return any uri, but gives
```
...
  <d:propstat>
   <d:prop>
    <d:uri/>
    <cal:uri/>
    <x1:uri xmlns:x1="http://apple.com/ns/ical/"/>
    <oc:uri/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
...
```
instead.

**Comment by DeepDiver1975** [comment]
> Can I query the Uri directly, or do I have to extract it from the url?

you have to extract it

**Comment by Henni** [comment]
I'm somehow missing JS files:
image

**Comment by Henni** [comment]
Adding a list with the name `hello` results in:

**owncloud.log:**
`Invalid Request (Malformed HTTP request)`

**Request payload:**
```
<c:mkcalendar xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:d="DAV:" xmlns:a="http://apple.com/ns/ical/" xmlns:o="http://owncloud.org/ns"><d:set><d:prop><d:displayname>hello</d:displayname><o:calendar-enabled>1</o:calendar-enabled><a:calendar-color>#FF7A66</a:calendar-color><c:supported-calendar-component-set><c:comp name="VTODO"/></c:supported-calendar-component-set></d:prop></d:set></c:mkcalendar>
```

**Response payload:**
[empty]

**DevTools console:**
image

**Comment by raimund-schluessler** [comment]
@Henni Sorry, I can't reproduce this. Creating a calendar with name "hello" works fine with OC 9.0.0 and the current DAVclient branch.

**Comment by onny** [comment]
Thank you Raimund for the hard work! Can't wait to use the new version! :+1:

**Comment by raghunayyar** [comment]
\o/

**Comment by raimund-schluessler** [comment]
With 8808e77056e1bbfb37f2637cb76f0b76cb22f027 we only load pending tasks. But this also means completed tasks are not loaded at all at the moment.

@DeepDiver1975 Is there a possibility to load the five newest completed tasks per list? And maybe also a query to get the total number of completed tasks at the server?

**Comment by DeepDiver1975** [comment]
CalDAV and carddav queries have no understanding of aggregation functions - we have been looking for this for Contacts already.
But getting the five newest should be possible this the  calendar query

**Comment by raimund-schluessler** [comment]
Hm, can someone give me a hint on how to limit and order the result set? My naive try to limit the result set to five didn't succeed and I don't seem to be able to figure it out by myself:
```xml
<c:calendar-query xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:d="DAV:" xmlns:a="http://apple.com/ns/ical/" xmlns:o="http://owncloud.org/ns">
   <d:prop>
      <d:getetag/>
      <c:calendar-data/>
   </d:prop>
   <d:limit>
      <d:nresults>5</d:nresults>
   </d:limit>
   <c:filter>
      <c:comp-filter name="VCALENDAR">
         <c:comp-filter name="VTODO">
            <c:prop-filter name="COMPLETED">
               <c:is-not-defined/>
            </c:prop-filter>
         </c:comp-filter>
      </c:comp-filter>
   </c:filter>
</c:calendar-query>
```
@Henni @georgehrke @DeepDiver1975

**Comment by georgehrke** [comment]
I don't think that CalDAV reports support limit and offset.
One way to do this is in two requests.
First one: send your request without `<c:calendar-data/>`
Second request: Take the hrefs from request one and send a multiget to the server

**Comment by raimund-schluessler** [comment]
I thought this was possible because of this: https://tools.ietf.org/html/rfc5323#section-5.17 Did I misunderstand it?

**Comment by georgehrke** [comment]
The webdav search extension has nothing to do with CalDAV and CardDAV reports.

**Comment by DeepDiver1975** [comment]
> I don't think that CalDAV reports support limit and offset.

indeed - only carddav query supports that ... my bad - sorry

**Comment by raimund-schluessler** [comment]
Merging this. Remaining problems are tracked in separate issues:

Timezone for start, due and reminder: https://github.com/owncloud/tasks/issues/312
Copying tasks: https://github.com/owncloud/tasks/issues/313
Setting reminder: https://github.com/owncloud/tasks/issues/314
Implement comment feature: https://github.com/owncloud/tasks/issues/315
Search: https://github.com/owncloud/tasks/issues/311

**Comment by janvonde** [comment]
will you release the app soon and add the features afterwards, or will you just continue to develop in the master branch and release the app when everything is done?

**Comment by raimund-schluessler** [comment]
As it was requested by several users, I will release a version to the appstore soon and indicate the yet missing features. So it is possible to install via the appstore again and everybody can decide whether or not he is willing to update.

**Comment by janvonde** [comment]
awesome! :+1:

**Comment by nickvergessen** [comment]
Thanks a lot @raimund-schluessler

**Comment by Gomez** [comment]
Great work @raimund-schluessler. :beers:  at ownCloudConf!

**Pull request merged**
