### PR TITLE
Add proper support of shared lists

### PR DESCRIPTION
**Pull request by sahne123**
This pull request shall fix the frontend issues with shared task lists(calendars). Right now the backend respects create/edit/delete privileges but the frontend acts like you can do whatever you want. See also  #108. 

Things we have to do:
- [x] Hide the add task input field if there is no create permissions on that list
- [x] Don't allow to complete tasks if there is no edit permission or the task is confidentialr
- [x] Don't allow to star tasks if there is no edit permission or the task is confidential
- [x] Don't allow to edit the task if there is no edit permission or the task is confidential
- [x] Don't allow to delete tasks if there is no delete permission or the task is confidential
- [ ] Remove Add Subtask button if there is no create permission on that list
- [ ] Solve Comments Problem
- [ ] Solve style issues
- [ ] Add checks to Drag 'n Drop

Maybe it's a good idea to make it anyhow visible for the user which permission he has.

I've started with the add task field. Please have look @Henni @raimund-schluessler @ouinouin @chaosjug

***edit***: There is a problem with the comments on tasks. Since the comments are stored in the VTODO backend don't allow to add comments if you don't have edit permissions. But comment on a shared readonly task should be possible or what do you think?

***edit2***: did some further changes. Now there are some style issues.
- no space on the right if there is an due date but no edit permission (star hidden)
- big spaces at the left because of hidden checkbox. I think its just a problem on a readonly lists where no task is editable (no checbox)
- cursor pointer on tasks with no edit permission (nothing happens on click)

***edit3***: It seems the backend allows to move tasks from on list to another without having proper permissions. Can someone please have a look and confirm this? As we use `\OC_Calendar_Object::moveToCalendar` it might be a bug there? 
https://github.com/owncloud/calendar/blob/master/lib/object.php#L333
For me the permission checks there make no sense at all. Don't we need DELETE permission at the source calendar and CREATE permission at the destination calendar? But maybe i'm just a bit tired and dont get it?

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@sahne123 Thanks a lot for working on this! Your code looks good so far, but I haven't had time to actually test it. Will do so later this week, I guess.

Regarding comments:
I think we should handle commenting as editing the task for now. Core does not support a separate permission just for commenting and I currently don't want to add an own, as you could not set/change this permission anywhere atm. And maybe someone wants to share a task, but prevent commenting which would not be possible if we just allow it by default. This is also related to https://github.com/owncloud/tasks/issues/169. So for now I would not separate edit/comment permissions but maybe create an issue for this in core (Since they also want to implement commenting on files, I think, this could be helpful).

Style issues:
Maybe we don't want to really hide those fields (checkbox, star, etc.) but show that they are disabled (e.g. by greying them out, set a different cursor, remove hover effects and so on)? @Henni @jancborchardt 

Backend moveToCalendar:
This would be my guess too. Changing the calendar means having DELETE (source) and CREATE (target) rights. Otherwise you could just annul the Delete and Create rights by moving to a different calendar and then do what you want to the task. I will have a look at the calendar backend. In the longterm we should get rid of all OC_Calendar_** calls anyway (handled in #228).

**Comment by jancborchardt** [comment]
@Henni do we want to check this out at the meetup today? :)

**Comment by Henni** [comment]
@jancborchardt that would be great!
@sahne123 can you rebase this please?

**Comment by sahne123** [comment]
@Henni Just did a rebase. Excuse the latency.

I agree with @raimund-schluessler about the comments issue and think we should also keep the moveToCalendar-Backend problem seperatly. Are there already issues created?

@Henni @jancborchardt  Have you talked about the styling?

Right now i am very busy with a project at work and can't work much on that.

**Comment by Henni** [comment]
@sahne123 thanks

I'm fine with the comments issue as well.

The `moveToCalendar` seems to be a calendar issue. Could you create an issue for it?

I'll take a look at the styling in the next few days.

**Comment by Henni** [comment]
- [ ] show different icon for shared list

This is how it currently looks like (no difference):
image

**Comment by Henni** [comment]
@sahne123 is it intended that I can't open the sidebar for shared tasks?

**Comment by raimund-schluessler** [comment]
This PR needs to be adjusted after we switched to the new DAV app in core and might be partly obsolete. Would be also possible to merge this first to have the necessary changes to the front-end and adjust the backend with #280.

@Henni @sahne123 Any opinions?

**Comment by agilob** [comment]
Sorry for nagging, but will there be any progress on this?

**Comment by Henni** [comment]
@agilob owncloud core is currently integrating CalDAV. Because of this we will have to rewrite a lot of this (https://github.com/owncloud/tasks/pull/247#issuecomment-158874898), but I'm currently working on other apps and @raimund-schluessler doesn't have that much time. I'm not sure if @sahne123 has time to work on this?!
To sum it up, there will be progress, but it will take a while.

But maybe you want to take a look, @agilob?

**Comment by agilob** [comment]
>But maybe you want to take a look, @agilob?

I don't know any language oc or tasks are written in :<

**Comment by keunes** [comment]
Thanks for your work on this so far folks. Hope the dependency on the Calendar app will removed (#280) within the foreseeable future ;)
Would really make owncloud + tasks app a killer combo!

**Comment by raimund-schluessler** [comment]
Superseded by #291.

Nearly all issues with reflecting the write privileges in the GUI are solved in the DAVclient branch. Only the drag-and-drop logic does not respect it at the front end yet.

**Pull request closed without merging**
