### PR TITLE
Remove calendar dependencies

### PR DESCRIPTION
**Pull request by raimund-schluessler**
We should remove all Dependencies on

- [ ] \OC_Calendar_Calendar
- [ ] \OC_Calendar_App
- [ ] \OC_Calendar_Object

#226 must be merged first

### CODE REVIEW

**Comment by dynek** [comment]
Will this PR make it so calendars and tasks are separate or it has a completely other purpose?

Thank you for creating and maintaining this app!

**Comment by raimund-schluessler** [comment]
This is intended to separate the two apps, but it will take some time.

Also, in order to fully separate them, the CalDAV backend currently provided by the calendar app has to be merged into oC core, which is not scheduled yet.

**Comment by dynek** [comment]
Thank you for your answer.

**Comment by Henni** [comment]
@raimund-schluessler what is the current state of this PR?

**Comment by raimund-schluessler** [comment]
This PR will be obsolete once we switch to the new DAV app in core. See #280.
--> Closed

**Pull request closed without merging**
