### PR TITLE
Response Trait

### PR DESCRIPTION
**Pull request by Henni**
This pull request adds a response trait as discussed in #205.
These changes unify the requests/responses as described in #196.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@Henni Thanks for the work, looks good in general. I fixed two small errors, I think after a rebase its good to merge. However, please take care to remove those two angularjs directives from your system:
https://github.com/owncloud/tasks/commit/3e13f15ba096ef538fcd77d1d700ccb543a0225e#diff-37bb856dc04e8c65595d2746df449090L342

https://github.com/owncloud/tasks/commit/3e13f15ba096ef538fcd77d1d700ccb543a0225e#diff-37bb856dc04e8c65595d2746df449090L361

Grunt doesnt delete deleted files automaticall, so javascript files build from coffescript reappear until you delete them manually. Regards!

**Comment by Henni** [comment]
Thanks for the fixes!

**Comment by Henni** [comment]
I'll rebase and merge it if that's ok with you @raimund-schluessler !?

**Comment by raimund-schluessler** [comment]
:+1:

**Comment by raimund-schluessler** [comment]
Nice, this really improved our code quality according to scrutinizer :)

**Pull request merged**
