### PR TITLE
check privacy settings for shared Tasks

### PR DESCRIPTION
**Pull request by sahne123**
As mentioned in #108 the task app didn't respect privacy settings for shared tasks. Fixed this part.
There is still the issue with editing tasks for readonly calendars.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Code looks reasonable. I will test asap. Failed test should be unrelated, see #197 .

**Comment by sahne123** [comment]
sorry for the "commit-mess". I literally didn't know what i am doing :o hope everything is fine now with the refactored taskservice  #195

**Comment by raimund-schluessler** [comment]
Code looks good in general, but we can't merge it like this, sorry. You can read about how to rebase here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request.

Or maybe, its better if you just prepare a new clean PR ;)

**Comment by sahne123** [comment]
Thanks for the link! Will fix this tomorrow.

**Pull request closed without merging**
