### PR TITLE
Add confirmation directive

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR add a confirmation dialog to the delete button of the calendar list to prevent accidental deletions. See this GIF for how it works:

directive2

After a click on "delete" a menu with a cancel button and a delete button appears. The delete button is activated after three seconds. Also an explaining tooltip is shown when you hover over the delete button.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Maybe this is also interesting for the calendar app? @georgehrke @jancborchardt

**Comment by georgehrke** [comment]
Hm, I like this idea, but I think we should go with the undo action as planned for the calendar.

**Comment by jancborchardt** [comment]
@raimund-schluessler hey, wait for a review please ;D Right now if you really want to delete some task lists you have to wait an annoying 3 seconds. And the long text as well as the X icon doesn’t help to understand.

As @georgehrke said we need to use undo instead. No confirmation.

**Comment by raimund-schluessler** [comment]
I am fine with removing this directive once an undo possibility is implemented. But until then, we need some sort of confirmation that the user really wants to delete the whole calendar and not accidentally misclicked. This directive replaces the previously used confirm method of the browser which blocked all interactions with the app. So this is definitly an improvement.

Also, how often do you really delete a calendar list? I did it maybe two times since I use owncloud. But even if you do it everyday, I still think that the hazzle of losing a complete calendar by accident is far worse than having to wait for 3 seconds.

I can remove the X button, though.

**Pull request merged**
