### PR TITLE
Implement categories

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Still some things to do:

- [x] fetch available categories from the server
- [x] fix deletion of last category
- [x] style category area including icons for categories and delete button
- [x] show categories in the task list directly
- [x] make sure select drop-down closes when clicking somewhere within the app (changes to event handling necessary, remove event.stopPropagation)
- [x] remove unused css code, check delete icon

- [x] add new categories to the available categories
- [ ] existing tasks now all have an empty category?

### CODE REVIEW

**Comment by Henni** [comment]
These changes look great.

I found three small issues:
* The delete icon for the categories seems to be missing (.../apps/tasks/css/vendor/angularui/ui-select/select2x2.png)
* every task which existed before the update now contains an empty category
* adding a custom category for one task doesn't add the new category to the autocompletion for other tasks. This requires a page reload.

The last problem should probably be fixed in its own issue as this isn't preventing the release of the feature.

**Comment by raimund-schluessler** [comment]
Thanks for the hints.

- First point is weird. I actually use the custom delete icon which is also used for deleting reminders, start date etc. So select2x2.png is not needed. I guess it should be enough to delete the link from the css code.
- This doesn't happen for my test installation. I will have a look at it. Probably I need further details.
- I will change this, shouldn't be a bigger issue. No need to release a broken feature ;)

**Comment by Henni** [comment]
I don't see any icon next to the categories:
taskscategories
Angular-UI seems to overwrite your css rule:
taskscategoriescancelcss

**Comment by raimund-schluessler** [comment]
Weird again, its not overwritten for my testing environment. Will check.

**Comment by Henni** [comment]
The problem only occurs if the pixel-ratio is over 1.5.
In this case the media-query of angular-ui is more specific than yours.

**Comment by raimund-schluessler** [comment]
Alright, thanks for the investigation.

**Comment by raimund-schluessler** [comment]
@Henni Is it possible that an other client set the category of all your tasks to a space character? The normal task created by the Tasks app looks like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar
CALSCALE:GREGORIAN
BEGIN:VTODO
CREATED:20150528T202712Z
UID:a2ce5684-eb01-48d0-84e7-b1c0d1677f32
LAST-MODIFIED:20150528T202712Z
DTSTAMP:20150528T202712Z
SUMMARY:Test
LOCATION:
DESCRIPTION:
CATEGORIES:
PRIORITY:
PERCENT-COMPLETE:0
END:VTODO
END:VCALENDAR
```
When you add a space character after ```CATEGORIES: ``` you will get one empty category. Could you check in your database if there is a space character? And does it also happen for newly created tasks?

**Comment by raimund-schluessler** [comment]
@Henni I would like to merge this today, altough there might be a problem with empty categories. Maybe you can have a look at your own, as I am not able to reproduce it anyway at the moment.

**Comment by Henni** [comment]
I tried to reproduce the problem and I checked out:
* the last commit before the categories branch (13ddc01)
* the last commit of the sabre-upgrade branch (c141545)
* the first commit of the sabre-upgrade branch (054ac0e)

I added a task in all of these states and all of them had the empty category.
Tasks I added while on the categories branch (1cd337d) didn't have this problem.

I'm not able to test previous commits as I don't have a development environment running on pre-8.1

**Comment by raimund-schluessler** [comment]
Hm, still weird. Categories are set to ```null``` when creating a task since the very first commit and I didn't change much about it later on. Acutally I haven't even changed something in the categories branch about creating a task. Also this doesn't happen for my installation.

1) Which database do you use? MySQL, PostgreSQL?
2) Can you check in your DB if there is a space character after the CATEGORIES property please?

The question is how we handle those empty categories. Technically they are a valid category, altough it doesn't make much sense. We could just check for such categories and simply delete them.

**Comment by Henni** [comment]
1) I'm using MySQL.
2) No there is no space character at the end of the CATEGORIES line.
I just found out that my last comment wasn't correct.
Even a task I added on the last commit of the categories branch (1cd337d) or now on the current master leads to an empty category (after reloading the page).

**Comment by irgendwie** [comment]
@Henni @raimund-schluessler I have the same problem!
* I use mysql and checked the database - there is **no** whitespace character at the end of the `CATEGORIES` line.
* If I add a few categories I'm left with this in the database:
`[...] CATEGORIES:,Anruf,Geburtstag [...]`
* Screenshot for reference:

2015-06-01-144748_309x160_scrot

**Pull request merged**
