### PR TITLE
Replaced deprecated moment.js functions

### PR DESCRIPTION
**Pull request by Henni**
Replaced all occurrences of lang() with locale().

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Did you test this? For me no dates are shown (e.g. for start and due date). Probably other things dont work either, but I didnt test it that much.

**Comment by Henni** [comment]
I tested it but probably missed something.
I'll look into it.

**Comment by Henni** [comment]
Should be fixed.
@raimund-schluessler please take a look

**Comment by raimund-schluessler** [comment]
Thanks @Henni, its working now!

**Pull request merged**
