### PR TITLE
Follow owncloud theme

### PR DESCRIPTION
**Pull request by Henni**
These are the first changes towards changing the theme to the default app design and fixing #102.

This pull request changes the styling of the navigation and removes the custom background in the content area.
Thereby some functionality (like hiding smart lists) is lost, but I will fix this soon.

There is still a lot to do. The next step is cleaning up the icon placing. Therefore I need the icons in seperate files opposed to all of them in a single sprite file.
@raimund-schluessler do you still have them somewhere or should I extract them from the sprite files.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Thanks for your work here!

As I don't know excatly what you will change here I will just give a list of all things I noticed (although you might have changed them anyway)

- No functionality must be lost ;)
- I have the icons in separate files, but I must say I think its not a good idea and praxis to separate the icons as it costs multiple server-requests and bandwidth to load them separately. Also it may cause flickering icons when they are changed dynamically (because the browser loads them on demand). At least this happened when I first tried it, don't know how it is today.
- Also the numbers of the lists must be aligned on the right. It looks terrible when they are left (especially for numbers with different numbers of digits). Hence, it may not be possible to keep the simple ```<ul><li><a>``` structure of the standard owncloud navigation bar anyway, I guess at least a floating ```<span>``` must be added for the numbers @jancborchardt 
- Can we keep the three dots at the left of the numbers (altough I don't know what they are doing, only had a look on the screenshot in #102).

Looking forward to the next changes. Regards!

**Comment by Henni** [comment]
Thanks for the feedback so far.

I need the icons in separate files to use them as intended by the [owncloud documentation](https://doc.owncloud.org/server/8.0/developer_manual/app/css.html). I think that extracting the images from the sprite within a background-image is not possible, but maybe I'm missing some CSS magic here ;) @jancborchardt 

We can also talk about these changes on IRC (#owncloud-tasks).

**Comment by raimund-schluessler** [comment]
Yes, I had a look at the files app. We could increase the spacing between the icons in the sprites file so that the other icons are not visible anymore, that's basically how sprite files are working anyway.

Separating the icons is a bit of work as I have them as .ai files (Adobe illustrator) and I need to export them all to svg and png then.

But let's here what @jancborchardt thinks.

**Comment by Henni** [comment]
I removed the modal window and instead moved all the settings to the bottom of the navigation.
But I think that the option to hide smart collections should probably be moved to the "3-dot" menu of the collections.

**Comment by raimund-schluessler** [comment]
I agree with removing the modal window. And the smart collections settings should indeed be moved to the 3-dot menu, otherwise the settings at the bottom will be overcharged.

**Comment by raimund-schluessler** [comment]
We could also remove the settings completely as the only setting left will be the "first day of week" and we could just adopt the setting from the calendar app @jancborchardt ?

**Comment by jancborchardt** [comment]
@raimund-schluessler regarding adopting settings from the Calendar app: You could, but ideally there is no inter-app dependency. Now I know that Tasks has a dependency on Calendar anyway because of CalDAV, but ideally we move that into core: https://github.com/owncloud/core/issues/5939

So for now (even though I'm very fond of removing settings ;) I would keep the setting there. You could of course take the value from the Calendar app as a default. :)

Regarding the icons and sprites - let's please keep this separate from this as it's a whole nother can to open. See https://github.com/owncloud/core/issues/15531

**Comment by jancborchardt** [comment]
So I would say let's take it step by step and merge this here in as soon as possible. :) Any improvements can be made incrementally in further pull requests - we shall not try to cram the whole change into one giant PR.

**Comment by Henni** [comment]
So is this ready to merge or are you missing some stuff @raimund-schluessler?
I will add further stuff in new pull requests when this is merged.

**Comment by raimund-schluessler** [comment]
I need to have a a look at your last commit.

But two points I remembered:
- Do the smart collections hide again?
- What about the icons? Did you extract them from the sprite file?

Also, some changes could collide with the category support in the other branch, as I plan to drastically change the event handling (which is dirty as it is now, to much event.stopPropagation() is used atm). Probably its better to first merge category support and then the theme changes, but I don't know for sure.
I hope to be ready to push the event handling to the branch this evening, so you can have a look at it.

**Comment by Henni** [comment]
Smart Collections aren't hiding yet. I will fix this in this pull request.
I didn't extract the icons. I left them as they are for now. I will do something about this in a future pull-request (either use separate icons or find a workaround to use the sprite).

I currently have a problem with event propagation as well. So maybe your changes will solve my problem.
How much will you change regarding event handling. Does this include changes in the navigation (e.g. the cancellation of renaming a list)?

I would love to talk about this and some other stuff in more detail. If you find some time maybe we can write on irc #owncloud-tasks.

**Comment by raimund-schluessler** [comment]
Thanks for fixing the hiding of the collections.

I can submit the icons as separate files, I will have to convert them to SVG/PNG. But I am OK with keeping it as it is for now and changing it later on.

Regarding the event handling I intend to remove all usages of the stop-event="click" directive which does event.stopPropagation(). This currently interferes with closing the category drop-down. I already thought of a solution which should work, but I don't know if it does solve your problem too. I intend to check if a click was already handled by an other event-handler and do nothing in this case. However, the event is still propagated down the DOM and any other handler can decide on its own if an action is required. I don't know if its the ideal solution, so lets have a look together.

I am currently not on IRC but I guess I should be ;). I am on holiday for a week starting on Saturday so I probably won't manage to set this up before, but I will definitely do so afterwards.

**Comment by Henni** [comment]
I already stumbled over stop-event='click' and I think that it's at least a part of my problem.
So I'm happy to wait for the category pull-request.

Looking forward to chatting with you ;)

**Comment by Henni** [comment]
This should complete the pull-request. I'm looking forward to feedback.

**Comment by raimund-schluessler** [comment]
Thanks, I will have a look asap.

In the meanwhile you can have a look at https://github.com/owncloud/tasks/commit/680e81858db97e3a6796f9b7c7e0de94724ff4c4 I reworked the event-handling and removed ```event.stopPropagation()``` The event-handler now checks if it is the closest handler to the element clicked by checking the DOM for elements with class 'handler'. If its not the closest handler the event is ignored except directly stated otherwise.

Let me hear if it solves your problems.

**Comment by raimund-schluessler** [comment]
The changes look really good. Some points I noticed though:

- renaming a task does not work atm, I guess this is the problem with the event-handling you mentioned
- the drop-downs of the selection whether a collection is shown or not should be aligned right. probably this can be skipped by moving these dropdowns to the 3-dot-menu
- I would switch ```app-navigation-entry-utils-counter``` and ```app-navigation-entry-utils-menu-button``` so that the counter is always in the right
- you will have to replace ```<label for="firstday">Start week on</label>``` with ```<label for="firstday"><?php p($l->t('Start week on')); ?></label>``` in order to have it translated correctly.

Apart from that the changes do look great, thanks for the good work. I intend to merge #172, so you can rebase against it and we can merge this PR here next.

**Comment by Henni** [comment]
Rebased onto the new master including the changes of the categories branch.
Additionally I fixed the translation issue (`<?php p($l->t('Start of week')); ?>`) and switched the counter and the menu-button.

I'm aware that the renaming doesn't work via the button in the menu, but renaming by double-clicking should work. This will hopefully change soon.
Should I change the alignment of the drop-downs or is this good enough until I move this option to the 3-dot menu?

**Comment by Henni** [comment]
Some part of the problems I had with event-handling seem to have been fixed by your changes.
But now I have a new issue:
When the input is active another click inside it results in closing the input. I think this happens because I moved the input inside an `<a>`-Tag and the click event bubbles up. I don't think your handler class is able to fix this issue. Can you tell me what exactly this class is for and how it should be used? @raimund-schluessler

**Comment by raimund-schluessler** [comment]
Thanks for rebasing. I guess we merge this now and create new issues for all problems. I would like to solve all those issues before releasing for oC8.1. Some problems might need tweaks in owncloud core (e.g. the problem with the misaligned options dropdown when switching counter and menu button)

**Comment by raimund-schluessler** [comment]
@Henni The handler class is used by the bound click handler to detect whether an event was already handled or not. E.g. here https://github.com/owncloud/tasks/blob/master/js/app/controllers/appcontroller.coffee#L52-L53 the handler works only if he is bound to the closes DOM element with "handler" class (or the element has the close-all class). I guess it should be possible to edit your event-handlers to do the same. I will have a look after we merged the PR.

**Comment by Henni** [comment]
@raimund-schluessler If it's ok with you I will merge this.

Regarding the sprite issue you described:
I see what you mean. I thought the browser (in my case chrome) would prefetch such images. Maybe it would be a good idea to group images in multiple sprites. For example to put both delete icons in a single file. But this should probably be discussed over at owncloud/core#15531.

The handler implementation looks a bit like you invented a replacement to how javascript handles events. What is the reason that you don't want to work with `preventDefault()` and `stopPropagation()`?

**Comment by raimund-schluessler** [comment]
@Henni Yeah, you can merge it, I saw you are a collaborator now :) So we can work on new features in branches now, which might simplify developing.

The sprites problem should really be discussed there, grouping related icons might be an option, at least to prevent flickering.

Regarding the handler: It is not a replacement, but a better practice. You can read about it e.g. here: https://css-tricks.com/dangers-stopping-event-propagation/ The main reason was that the multi-select which is used for the categories need to detect clicks for closing the dropdown. This is not possible with ```stopPropagation()``` as the handler doesn't see the click at all. With the class every handler can decide on its own whether or not to react on a click.

**Comment by Henni** [comment]
Thanks for the link. That really cleared things up for me.

**Comment by jancborchardt** [comment]
Great stuff here! :) Awesome work @Henni, good to see you collaborating with @raimund-schluessler so we can have one great Tasks app.

About the »menu or counter on the right in the sidebar« thing – yeah, we need to kinda think about that in core, also for the News app, and sooner or later for Mail etc. cc @Raydiation. For now, the counter can move.

**Comment by jancborchardt** [comment]
Btw @Henni @raimund-schluessler there’s an IRC channel #owncloud-tasks so you can chat and also invite more collaborators to. :)

**Pull request merged**
