### PR TITLE
Update for Sabre 2.1

### PR DESCRIPTION
**Pull request by PVince81**
- get rid of OC_VObject
- adapt date handling
- replace setString/getAsString usages

This is needed for the app to work with (core/master) and the upcoming 8.1 which contains the Sabre upgrade to 2.1.

Note: the app still doesn't work and I don't know, needs more debugging

### CODE REVIEW

**Comment by PVince81** [comment]
@raimund-schluessler do you mind helping to finish this ?

I applied all the changes for the Sabre update which I knew from upgrading the calendar app.

**Comment by raimund-schluessler** [comment]
Thank you very much. I will have a look into this, but it will take probably 3 weeks as said in https://github.com/owncloud/core/pull/15691. If I find time, I try to take care sooner, but can't promise anything. Sorry.

**Comment by PVince81** [comment]
I think 3 weeks should be fine. If I find some time I'll see if I can fix the rest myself in the meantime.

**Comment by Henni** [comment]
It seems that the requests
```
http://localhost:8080/index.php/apps/tasks/tasks/init/all
http://localhost:8080/index.php/apps/tasks/tasks/add
```
are empty.
Whereas other requests like
```
http://localhost:8080/index.php/apps/tasks/lists
```
seem to work.

I'll have a look into this.

**Comment by Henni** [comment]
The problem seems to be that there are recursions in the returned JSON.
Because of that the returned object is extremely large or can't be returned at all.
Casting most of the fields to string resolves this issue.

**Comment by raimund-schluessler** [comment]
https://github.com/owncloud/tasks/commit/ad2e16a7de17c558ce89ce61f844e6437de99dd5 fixes the parsing of categories, reminders, comments and the percent value of completion.

But I haven't tested the creation of all those things yet.

**Comment by raimund-schluessler** [comment]
As of https://github.com/owncloud/tasks/commit/177781e4df6a407d62406c45494242ad697a7912 everything (I tested) seems to work with current core master.

Would be good if somebody else could test as well.

**Comment by Henni** [comment]
I'll test this tomorrow.

**Comment by Henni** [comment]
I found a problem with adding comments ( see PR #167 ).

The rest seems fine.

**Pull request merged**
